name: Finding You Home
favicon: null
layout_spectrum: 0.9528875628020614
typography_spectrum: 0.5303202620707452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9175847747828811
  lightness: 0.9694478646852076
  saturation: 0.19514921214431524
  rhythmicContrast: 0.7248159074224532
purpose: []
